### ISSUE TITLE
hi! I have tried to run the code but I really can't solve the following problem. I have java installed and have set the environment path. But It still can't work.

### ISSUE THREAD

**Issue by Lanskttee** [ltl3A87/KB-BINDER#2]
Traceback (most recent call last):
  File "D:\pycharm\KB-BINDER-main\few_shot_kbqa.py", line 12, in <module>
    from pyserini.search import FaissSearcher, LuceneSearcher
  File "D:\pycharm\venv\lib\site-packages\pyserini\search\__init__.py", line 17, in <module>
    from ._base import JQuery, JQueryGenerator, JDisjunctionMaxQueryGenerator, get_topics,\
  File "D:\pycharm\venv\lib\site-packages\pyserini\search\_base.py", line 26, in <module>
    from pyserini.pyclass import autoclass
  File "D:\pycharm\venv\lib\site-packages\pyserini\pyclass.py", line 27, in <module>
    from jnius import autoclass, cast
  File "D:\pycharm\venv\lib\site-packages\jnius\__init__.py", line 18, in <module>
    java = get_java_setup(sys.platform)
  File "D:\pycharm\venv\lib\site-packages\jnius\env.py", line 60, in get_java_setup
    JAVA_HOME = get_jdk_home(platform)
  File "D:\pycharm\venv\lib\site-packages\jnius\env.py", line 335, in get_jdk_home
    raise Exception('Unable to find JAVA_HOME')
Exception: Unable to find JAVA_HOME

**Comment by Lanskttee** [comment]
hi! I've solve the above problem. Unfortunatelly, I met another one:

  File "jnius\jnius_export_func.pxi", line 22, in jnius.find_javaclass
  File "jnius\jnius_utils.pxi", line 79, in jnius.check_exception
jnius.JavaException: JVM exception occurred: org/apache/lucene/search/Query has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 java.lang.UnsupportedClassVersionError


I both try the java8 and java11. But neither can help to solve this.

**Comment by MXueguang** [comment]
could you try install the java environment with
`conda install -c conda-forge openjdk=11`
the above error comes from the pyserini dependency
https://github.com/castorini/pyserini/blob/master/docs/installation.md

**Comment by Lanskttee** [comment]
> could you try install the java environment with `conda install -c conda-forge openjdk=11` the above error comes from the pyserini dependency https://github.com/castorini/pyserini/blob/master/docs/installation.md

Thanks for your help. Actually, I have installed the oracle jdk11. Is the version leads to the mistake?

If I type java --version in a shell, it says:

java 11.0.19 2023-04-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.19+9-LTS-224)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.19+9-LTS-224, mixed mode)

**Comment by Maydaytyh** [comment]
> could you try install the java environment with `conda install -c conda-forge openjdk=11` the above error comes from the pyserini dependency https://github.com/castorini/pyserini/blob/master/docs/installation.md

I notice that [hyde](https://github.com/texttron/hyde) repos have the index for FaissSearcher, can you provide it for KB-BINDER or the way to get it? Thank you!

**Comment by thelastNYF** [comment]
It seems that Java 21 is required.
